[package]
name = "yew-octicons-example-icon-sizing"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2021"

[dependencies]
yew-octicons = { path = "../../yew-octicons" }
yew = "0.19.3"
wasm-bindgen = "0.2.78"

[lib]
crate_type = ["cdylib"]
