name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run tests
        run: cargo test

  clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run clippy
        run: cargo clippy -- -D warnings

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check formatting
        run: cargo fmt --all -- --check

  example:
    name: Build example page
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Download trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build example
        run: ./trunk build --public-url "/yew-octicons" --release examples/icon-sizing/index.html
