name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run tests
        run: cargo test

  example:
    name: Build example page
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build example
        run: ./examples/icon-sizing/build.sh
