name: Deploy example

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-example:
    name: Deploy example to GitHub Pages
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Download trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build example
        run: ./trunk build --public-url "/yew-octicons" --release examples/icon-sizing/index.html

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: examples/icon-sizing/dist
