name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run tests
        run: cargo test

  example-deploy-pages:
    name: Deploy example to GitHub pages
    runs-on: ubuntu-latest
    steps:

      - name: Pull source
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build example
        run: ./examples/icon-sizing/build.sh

      - name: Delete pkg/.gitignore to prevent deployment from failing
        run: rm -f ./examples/icon-sizing/static/pkg/.gitignore

      - name: Push to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: examples/icon-sizing/static
